import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./{component}/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Ticket App",
	description: "Generated by Wei",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
